// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleTitle': string;
  'articleWrapper': string;
  'containerAbsolute': string;
  'containerArticle': string;
  'containerDetail': string;
  'containerImg': string;
  'containerRelative': string;
  'itemImg': string;
}
export const cssExports: CssExports;
export default cssExports;
