// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardContent': string;
  'cardDate': string;
  'cardSummary': string;
  'cardTitle': string;
  'containerHome': string;
  'divider': string;
  'filter': string;
  'filterWrapper': string;
  'link': string;
  'textField': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
